name: Next.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: |
          magarni-dd-ko-achar/node_modules
          magarni-dd-ko-achar/.next/cache
        key: ${{ runner.os }}-node-${{ hashFiles('magarni-dd-ko-achar/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd magarni-dd-ko-achar
        npm install
        npm run dev
